# Generated by Django 2.2.24 on 2021-11-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(verbose_name='date published')),
                ('activation_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_status', models.BooleanField(default=True)),
                ('doc_conversion_allowed', models.ManyToManyField(to='service.DocType')),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_type', to='service.DocType')),
            ],
        ),
    ]
